### ISSUE TITLE
using of <br> element

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex7-digital_dynasty#6]
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g28d48e53e08_0_139

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/norona_marynicole/act.html#L40C7-L72C13

**Comment by Villa-VillaDiana** [comment]
Instead of using the <br> tag, consider using CSS for styling @Reyes-PaulAngelo 

https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L60
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L61
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L68
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L69
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L74
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L75
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L82
https://github.com/PUP-BSIT/ex7-digital_dynasty/blob/c9d47da24700cd6b08706e82bd71c8592a812a95/Reyes_PaulAngelo/Reyes_Paul-Angelo.html#L83

**Comment by norona-marynicole** [comment]
Thank you po!

**Comment by bergado-shamma** [comment]
Thank you po 💙
